#@ load("@ytt:data", "data")

#@ load("@ytt:base64", "base64")

apiVersion: v1
data:
  password: #@ base64.encode(data.values.usersMongoPassword)
kind: Secret
metadata:
  creationTimestamp: null
  name: users-mongo-pass
  namespace: #@ data.values.nameSpaceFE