#@ load("@ytt:data", "data")

#@ load("@ytt:base64", "base64")

apiVersion: v1
data:
  password: #@ base64.encode(data.values.orderPostgresPassword)
kind: Secret
metadata:
  creationTimestamp: null
  name: order-postgres-pass
  namespace: #@ data.values.nameSpaceFE