apiVersion: v1
kind: Service
metadata:
  name: catalog-mongo
  namespace: acme-fitness
  labels:
    app: acmefit
    service: catalog-db
spec:
  ports:
  - port: 27017
    name: mongo-catalog
    protocol: TCP
  selector:
    app: acmefit
    service: catalog-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-mongo
  namespace: acme-fitness
  labels:
    app: acmefit
    service: catalog-db
spec:
  selector:
    matchLabels:
      app: acmefit
      service: catalog-db
  replicas: 1
  template:
    metadata:
      labels:
        app: acmefit
        service: catalog-db
    spec:
      containers:
      - name: catalog-mongo
        image: 10.220.38.244/test-env/mongo:4
        resources: {}
        ports:
        - name: catalog-mongo
          containerPort: 27017
          protocol: TCP
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongoadmin
        - name: MONGO_INITDB_DATABASE
          value: acmefit
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: catalog-mongo-pass
              key: password
        volumeMounts:
        - mountPath: /data/db
          name: mongodata
        - mountPath: /docker-entrypoint-initdb.d
          name: mongo-initdb
      imagePullSecrets:
      - name: test-env-default-image-pull-secret
      volumes:
      - name: mongodata
        emptyDir: {}
      - name: mongo-initdb
        configMap:
          name: catalog-initdb-config
